// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Readability",
    defaultLocalization: "en",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Readability",
            targets: ["App"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lightningBolt),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This is to track your eyes’ location")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                "Guide"
            ],
            path: "App",
            resources: [
                .process("Resources")
            ]
        ),
        .target(
            name: "Guide",
            path: "Guide",
            resources: [
                .process("Guide.tutorial"),
                .process("Resources/composability@2x.png"),
                .process("Resources/creating-new-swiftui-views@2x.png"),
                .process("Resources/experiment-with-swiftui@2x.png"),
                .process("Resources/get-started-with-apps@2x.png"),
                .process("Resources/modifying-swift-ui-views@2x.png"),
                .process("Resources/swift-ui-views@2x.png")
            ]
        )
    ]
)
